### ISSUE TITLE
Jupyter lab 3 compatibility

### ISSUE THREAD

**Issue by 915-Misan-Teodora** [XpressAI/xircuits#298]
**What kind of bug is it?**
- [x] Xircuits Core (Jupyterlab related features)
- [ ] Xircuits Canvas (Custom RD related features)
- [ ] Xircuits Component Library
- [ ] Testing Automation
- [x] Documentation
- [ ] Not Sure

**Xircuits Version**
Latest versions 1.10.*

**Describe the bug**
I am trying to run xircuits with jupyterlab 3. It appears as if the extension not even enabled in lab. 
I read through the xircuits release notes and it is not clear to me if it should be compatible with lab 3, or only lab 4?

**Expected behavior**
The xircuits icon in lab GUI does not appear in jupyter lab 3

**Tested on?**

- [x] Windows  
- [ ] Linux Ubuntu 
- [ ] Centos 
- [ ] Mac  
- [ ] Others  (State here -> xxx )

**Comment by MFA-X-AI** [comment]
Hi!
The newest version 1.10.* of Xircuits runs on Jupyterlab 4. Version 1.9 should still be on Jupyterlab 3. 

Take note that if you `pip install xircuits`, you'll need to launch it via `xircuits` for the first time instead of `jupyter lab` since it performs a few init operations in your working directory. Give it a try and let us know if you still run into problems.

**Comment by 915-Misan-Teodora** [comment]
Thank you for the explanation, it sounds reasonable.
